export const siteConfig = {
	name: "socius",
	description: {
		short: "scenarios for ai addressing humanity's challenges",
		long: "scenarios for ai addressing humanity's challenges - evaluating artificial intelligence on ethical reasoning, critical thinking, and cultural awareness to address real-world human problems",
	},
	socials: [
		{
			name: "GitHub",
			url: "https://github.com/adiadd/socius",
			icon: "github",
		},
		{
			name: "Twitter",
			url: "https://twitter.com/agnilabs",
			icon: "twitter",
		},
	],
	creator: {
		name: "agni labs",
		url: "https://agnilabs.xyz",
		twitter: "@agnilabs",
	},
	locale: "en_US",
	url: "https://socius.agnilabs.xyz",
	keywords: [
		"socius",
		"agnilabs",
		"ai scenarios",
		"ethical ai",
		"human-centered ai",
		"anthropocentric",
		"ai evaluation",
		"critical thinking",
		"ethical reasoning",
		"cultural awareness",
		"responsible ai",
		"ai ethics",
		"ai research",
		"collaborative problem-solving",
		"ai assessment",
		"human challenges",
		"ai for humanity",
		"social impact ai",
		"ethical technology",
		"ai performance metrics",
	],
};
